# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Tilus addon for TVM-FFI."""

# ruff: noqa: F405, RUF022

from __future__ import annotations

from . import _tilus_lang as _tilus_lang
from . import ir, transforms
from .ir import *

__all__: list[str] = [
    "ir",
    "transforms",
    "GlobalTensor",
    "RegisterTensor",
    "SharedTensor",
    "TMemoryTensor",
    "Tensor",
    "global_tensor",
    "register_tensor",
    "shared_tensor",
    "tmemory_tensor",
    "GlobalLayout",
    "Layout",
    "RegisterLayout",
    "SharedLayout",
    "Swizzle",
    "TMemoryLayout",
    "global_column_major",
    "global_layout",
    "global_row_major",
    "prod",
    "register_layout",
    "register_row_major",
    "register_spatial_row_major",
    "shared_column_major",
    "shared_layout",
    "shared_row_major",
    "tmemory_layout",
    "tmemory_row_major",
    "Evaluate",
    "InstStmt",
    "TensorItemPtr",
    "TensorItemValue",
    "ThreadGroup",
    "thread_group",
    "Instruction",
    "InstructionError",
    "AtomicSharedInst",
    "AtomicGlobalInst",
    "AtomicScatterSharedInst",
    "AtomicScatterGlobalInst",
    "ClusterLaunchControlTryCancelInst",
    "ClusterLaunchControlQueryResponseInst",
    "ClusterSyncThreadsInst",
    "CopyAsyncInst",
    "CopyAsyncGenericInst",
    "CopyAsyncCommitGroupInst",
    "CopyAsyncWaitGroupInst",
    "CopyAsyncWaitAllInst",
    "CopyAsyncBulkGlobalToSharedInst",
    "CopyAsyncBulkGlobalToClusterSharedInst",
    "CopyAsyncBulkSharedToGlobalInst",
    "CopyAsyncBulkSharedToClusterSharedInst",
    "CopyAsyncBulkCommitGroupInst",
    "CopyAsyncBulkWaitGroupInst",
    "CopyAsyncTensorGlobalToSharedInst",
    "CopyAsyncTensorSharedToGlobalInst",
    "CopyAsyncTensorCommitGroupInst",
    "CopyAsyncTensorWaitGroupInst",
    "FenceProxyAsync",
    "FenceProxyAsyncRelease",
    "MapSharedAddrInst",
    "AllocBarrierInst",
    "ArriveBarrierInst",
    "ArriveExpectTxBarrierInst",
    "WaitBarrierInst",
    "ArriveExpectTxMulticastBarrierInst",
    "ArriveExpectTxRemoteBarrierInst",
    "DotInst",
    "AtomicMmaConfig",
    "LockSemaphoreInst",
    "ReleaseSemaphoreInst",
    "SimtDotInst",
    "Tcgen05AllocInst",
    "Tcgen05DeallocInst",
    "Tcgen05RelinquishAllocPermitInst",
    "Tcgen05SliceInst",
    "Tcgen05ViewInst",
    "Tcgen05LoadInst",
    "Tcgen05StoreInst",
    "Tcgen05WaitInst",
    "Tcgen05CopyInst",
    "Tcgen05CommitInst",
    "Tcgen05MmaSSInst",
    "Tcgen05MmaTSInst",
    "WgmmaFenceInst",
    "WgmmaCommitGroupInst",
    "WgmmaWaitGroupInst",
    "WgmmaMmaSSInst",
    "WgmmaMmaRSInst",
    "AddInst",
    "CastInst",
    "DivInst",
    "LoadGlobalInst",
    "LoadSharedInst",
    "MulInst",
    "NopInst",
    "ReduceInst",
    "StoreGlobalInst",
    "StoreSharedInst",
    "SubInst",
    "SyncThreadsInst",
    "AnnotateLayoutInst",
    "AssumeInst",
    "Analysis",
    "Function",
    "Metadata",
    "DELETE_STMT",
    "IRFunctor",
    "IRRewriter",
    "IRVisitor",
    "StmtSplice",
    "RegTensor",
    "Eval",
    "Inst",
    "AtomicShared",
    "AtomicGlobal",
    "AtomicScatterShared",
    "AtomicScatterGlobal",
    "ClcTryCancel",
    "ClcQueryResponse",
    "ClusterSyncThreads",
    "CopyAsync",
    "CopyAsyncGeneric",
    "CopyAsyncCommitGroup",
    "CopyAsyncWaitGroup",
    "CopyAsyncWaitAll",
    "CopyAsyncBulkGlobalToShared",
    "CopyAsyncBulkGlobalToClusterShared",
    "CopyAsyncBulkSharedToGlobal",
    "CopyAsyncBulkSharedToClusterShared",
    "CopyAsyncBulkCommitGroup",
    "CopyAsyncBulkWaitGroup",
    "CopyAsyncTensorGlobalToShared",
    "CopyAsyncTensorSharedToGlobal",
    "CopyAsyncTensorCommitGroup",
    "CopyAsyncTensorWaitGroup",
    "MapSharedAddr",
    "AllocBarrier",
    "ArriveBarrier",
    "ArriveExpectTxBarrier",
    "WaitBarrier",
    "ArriveExpectTxMulticastBarrier",
    "ArriveExpectTxRemoteBarrier",
    "Dot",
    "LockSemaphore",
    "ReleaseSemaphore",
    "SimtDot",
    "Tcgen05Alloc",
    "Tcgen05Dealloc",
    "Tcgen05RelinquishAllocPermit",
    "Tcgen05Slice",
    "Tcgen05View",
    "Tcgen05Load",
    "Tcgen05Store",
    "Tcgen05Wait",
    "Tcgen05Copy",
    "Tcgen05Commit",
    "Tcgen05MmaSS",
    "Tcgen05MmaTS",
    "WgmmaFence",
    "WgmmaCommitGroup",
    "WgmmaWaitGroup",
    "WgmmaMmaSS",
    "WgmmaMmaRS",
    "Add",
    "Cast",
    "Div",
    "LoadGlobal",
    "LoadShared",
    "Mul",
    "Nop",
    "Reduce",
    "StoreGlobal",
    "StoreShared",
    "Sub",
    "SyncThreads",
    "AnnotateLayout",
    "Assume",
]

_PUBLIC_LANG_NAMES = (
    "Swizzle",
    "RegisterLayout",
    "SharedLayout",
    "GlobalLayout",
    "TMemoryLayout",
    "RegTensor",
    "RegisterTensor",
    "SharedTensor",
    "GlobalTensor",
    "TMemoryTensor",
    "Eval",
    "Inst",
    "AtomicShared",
    "AtomicGlobal",
    "AtomicScatterShared",
    "AtomicScatterGlobal",
    "ClcTryCancel",
    "ClcQueryResponse",
    "ClusterSyncThreads",
    "CopyAsync",
    "CopyAsyncGeneric",
    "CopyAsyncCommitGroup",
    "CopyAsyncWaitGroup",
    "CopyAsyncWaitAll",
    "CopyAsyncBulkGlobalToShared",
    "CopyAsyncBulkGlobalToClusterShared",
    "CopyAsyncBulkSharedToGlobal",
    "CopyAsyncBulkSharedToClusterShared",
    "CopyAsyncBulkCommitGroup",
    "CopyAsyncBulkWaitGroup",
    "CopyAsyncTensorGlobalToShared",
    "CopyAsyncTensorSharedToGlobal",
    "CopyAsyncTensorCommitGroup",
    "CopyAsyncTensorWaitGroup",
    "FenceProxyAsync",
    "FenceProxyAsyncRelease",
    "MapSharedAddr",
    "AllocBarrier",
    "ArriveBarrier",
    "ArriveExpectTxBarrier",
    "WaitBarrier",
    "ArriveExpectTxMulticastBarrier",
    "ArriveExpectTxRemoteBarrier",
    "Dot",
    "AtomicMmaConfig",
    "LockSemaphore",
    "ReleaseSemaphore",
    "SimtDot",
    "Tcgen05Alloc",
    "Tcgen05Dealloc",
    "Tcgen05RelinquishAllocPermit",
    "Tcgen05Slice",
    "Tcgen05View",
    "Tcgen05Load",
    "Tcgen05Store",
    "Tcgen05Wait",
    "Tcgen05Copy",
    "Tcgen05Commit",
    "Tcgen05MmaSS",
    "Tcgen05MmaTS",
    "WgmmaFence",
    "WgmmaCommitGroup",
    "WgmmaWaitGroup",
    "WgmmaMmaSS",
    "WgmmaMmaRS",
    "Add",
    "Cast",
    "Div",
    "LoadGlobal",
    "LoadShared",
    "Mul",
    "Nop",
    "Reduce",
    "StoreGlobal",
    "StoreShared",
    "Sub",
    "SyncThreads",
    "AnnotateLayout",
    "Assume",
)

for _name in _PUBLIC_LANG_NAMES:
    globals()[_name] = getattr(_tilus_lang.TilusLang, _name)

del _PUBLIC_LANG_NAMES, _name
