# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""FFI API for the standard dialect."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from .registry import init_ffi_api as _FFI_INIT_FUNC

_FFI_INIT_FUNC("ffi.std", __name__)

if TYPE_CHECKING:

    def cast(ty: Any, value: Any, /) -> Any: ...
    def add(lhs: Any, rhs: Any, /) -> Any: ...
    def sub(lhs: Any, rhs: Any, /) -> Any: ...
    def mul(lhs: Any, rhs: Any, /) -> Any: ...
    def cdiv(lhs: Any, rhs: Any, /) -> Any: ...
    def cmod(lhs: Any, rhs: Any, /) -> Any: ...
    def truncdiv(lhs: Any, rhs: Any, /) -> Any: ...
    def truncmod(lhs: Any, rhs: Any, /) -> Any: ...
    def floordiv(lhs: Any, rhs: Any, /) -> Any: ...
    def floormod(lhs: Any, rhs: Any, /) -> Any: ...
    def pow(lhs: Any, rhs: Any, /) -> Any: ...
    def min(lhs: Any, rhs: Any, /) -> Any: ...
    def max(lhs: Any, rhs: Any, /) -> Any: ...
    def eq(lhs: Any, rhs: Any, /) -> Any: ...
    def ne(lhs: Any, rhs: Any, /) -> Any: ...
    def le(lhs: Any, rhs: Any, /) -> Any: ...
    def ge(lhs: Any, rhs: Any, /) -> Any: ...
    def gt(lhs: Any, rhs: Any, /) -> Any: ...
    def lt(lhs: Any, rhs: Any, /) -> Any: ...
    def equal(lhs: Any, rhs: Any, /) -> Any: ...
    def not_equal(lhs: Any, rhs: Any, /) -> Any: ...
    def less_equal(lhs: Any, rhs: Any, /) -> Any: ...
    def greater_equal(lhs: Any, rhs: Any, /) -> Any: ...
    def less(lhs: Any, rhs: Any, /) -> Any: ...
    def greater(lhs: Any, rhs: Any, /) -> Any: ...
    def logical_and(lhs: Any, rhs: Any, /) -> Any: ...
    def logical_or(lhs: Any, rhs: Any, /) -> Any: ...
    def left_shift(lhs: Any, rhs: Any, /) -> Any: ...
    def right_shift(lhs: Any, rhs: Any, /) -> Any: ...
    def bitwise_and(lhs: Any, rhs: Any, /) -> Any: ...
    def bitwise_or(lhs: Any, rhs: Any, /) -> Any: ...
    def bitwise_xor(lhs: Any, rhs: Any, /) -> Any: ...
    def neg(operand: Any, /) -> Any: ...
    def logical_not(operand: Any, /) -> Any: ...
    def bitwise_not(operand: Any, /) -> Any: ...
    def bitwise_neg(operand: Any, /) -> Any: ...
    def abs(operand: Any, /) -> Any: ...
    def if_then_else(cond: Any, then_expr: Any, else_expr: Any, /) -> Any: ...
    def select(cond: Any, then_expr: Any, else_expr: Any, /) -> Any: ...
    def _AnalyzerCanProve(analyzer: Any, cond: Any, strength: Any, /) -> Any: ...
    def _AnalyzerCanProveEqual(analyzer: Any, lhs: Any, rhs: Any, /) -> Any: ...
    def _AnalyzerSimplify(analyzer: Any, expr: Any, steps: Any, /) -> Any: ...
    def _AnalyzerConstIntBound(analyzer: Any, expr: Any, /) -> Any: ...
    def _AnalyzerModularSet(analyzer: Any, expr: Any, /) -> Any: ...
    def _AnalyzerRewriteSimplify(analyzer: Any, expr: Any, /) -> Any: ...
    def _AnalyzerCanonicalSimplify(analyzer: Any, expr: Any, /) -> Any: ...
    def _AnalyzerIntervalSet(analyzer: Any, expr: Any, dom_map: Any, /) -> Any: ...
    def _AnalyzerConstIntBoundUpdate(
        analyzer: Any,
        var: Any,
        info: Any,
        allow_override: Any,
        /,
    ) -> None: ...
    def _AnalyzerGetEnabledExtensions(analyzer: Any, /) -> Any: ...
    def _AnalyzerSetEnabledExtensions(analyzer: Any, flags: Any, /) -> None: ...
    def _AnalyzerEnterConstraint(analyzer: Any, constraint: Any, /) -> Any: ...
