# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Sibling-``.pyi`` writer for finalized dialect modules.

Whenever ``tvm_ffi.dialect_autogen.finalize_module`` runs with
``auto_stub=True``, it calls :func:`write_dialect_stub` to regenerate
the dialect's type-stub file. The output is deterministic and grouped
into clearly-labelled sections so ``git diff`` is readable.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

# Local imports to avoid a cycle: ``dialect_autogen`` imports this file
# at call time inside ``finalize_module``. Importing those names back
# here at module top level would deadlock the import graph; deferring
# inside ``generate_dialect_stub`` avoids it.

_HEADER = """# Auto-generated by tvm_ffi.dialect_autogen.finalize_module
# Do not edit by hand. Re-run finalize_module() to regenerate.

from typing import Any, Callable
"""


def generate_dialect_stub(module: Any) -> str:  # noqa: PLR0912, PLR0915
    """Render the ``.pyi`` text for a finalized dialect ``module``.

    Returns the stub content as a string. Used by :func:`write_dialect_stub`
    and by tests that want to assert on the generated text without
    touching disk.
    """
    from .._parse_decorators import (  # noqa: PLC0415 — see module-level note
        RESERVED_DICT_SLOTS,
        RESERVED_FN_SLOTS,
        get_hook_spec,
    )
    from ..dialect_autogen import (  # noqa: PLC0415 — see module-level note
        DEFAULT_DTYPE_NAMES,
        _DtypeHandle,
    )

    # Categorize names. We intentionally do not import the full
    # registered_names() helper here; the .pyi must reflect what is
    # *actually* set on the module object so user-supplied names are
    # included alongside auto-registered placeholders.
    classes: list[str] = []
    dtype_handles: list[str] = []
    fn_slots: list[str] = []
    dict_slots: list[str] = []
    free_callables: list[str] = []
    other: list[tuple[str, str]] = []  # (name, hint)

    for name, value in sorted(module.__dict__.items()):
        if name.startswith("__") and name.endswith("__"):
            if name in RESERVED_FN_SLOTS:
                fn_slots.append(name)
            elif name in RESERVED_DICT_SLOTS:
                dict_slots.append(name)
            elif name == "__ffi_parse_default_dtypes__":
                other.append((name, "dict[str, str]"))
            continue
        if isinstance(value, type):
            # Only re-export classes declared in this dialect.
            if getattr(value, "__module__", None) == module.__name__:
                classes.append(name)
            continue
        if isinstance(value, _DtypeHandle):
            dtype_handles.append(name)
            continue
        if callable(value) and (
            getattr(value, "__ffi_parse_placeholder__", False) or get_hook_spec(value) is not None
        ):
            free_callables.append(name)
            continue
        # Skip everything else (constants, modules, etc.). The
        # registration walk doesn't claim those.

    lines: list[str] = [_HEADER]

    if classes:
        lines.append("# --- IR class re-exports ---")
        for name in classes:
            lines.append(f"class {name}: ...")
        lines.append("")

    if dtype_handles:
        lines.append("# --- dtype handles ---")
        # Order by the canonical DEFAULT_DTYPE_NAMES sequence first; any
        # extended dtypes follow alphabetically.
        ordered = [n for n in DEFAULT_DTYPE_NAMES if n in dtype_handles] + sorted(
            n for n in dtype_handles if n not in DEFAULT_DTYPE_NAMES
        )
        for name in ordered:
            lines.append(f"{name}: Any")
        lines.append("")

    if fn_slots:
        lines.append("# --- reserved C0 parser-protocol slots ---")
        for name in fn_slots:
            lines.append(f"{name}: Callable[..., Any]")
        lines.append("")

    if dict_slots:
        lines.append("# --- reserved C0 dict-typed slots ---")
        for name in dict_slots:
            value_type = (
                "dict[int, Callable[..., Any]]"
                if name == "__ffi_parse_op__"
                else "dict[str, Callable[..., Any]]"
            )
            lines.append(f"{name}: {value_type}")
        lines.append("")

    if free_callables:
        lines.append("# --- registered parser dispatchers ---")
        for name in free_callables:
            lines.append(f"def {name}(*args: Any, **kwargs: Any) -> Any: ...")
        lines.append("")

    if other:
        lines.append("# --- module-level metadata ---")
        for name, hint in other:
            lines.append(f"{name}: {hint}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_dialect_stub(module: Any) -> str:
    """Write the rendered ``.pyi`` next to the dialect module's source file.

    Returns the path written to. If the dialect lacks a real ``__file__``
    (e.g. it's a synthetic test module), this is a no-op and returns ``""``.
    """
    src = getattr(module, "__file__", None)
    if not src or not src.endswith(".py"):
        return ""
    pyi_path = Path(src[:-3] + ".pyi")
    content = generate_dialect_stub(module)
    # Only write when content changes; preserves mtime for unchanged
    # stubs and keeps ``make`` / pyright caches happy.
    try:
        existing = pyi_path.read_text(encoding="utf-8")
        if existing == content:
            return str(pyi_path)
    except OSError:
        pass
    pyi_path.parent.mkdir(parents=True, exist_ok=True)
    pyi_path.write_text(content, encoding="utf-8")
    return str(pyi_path)
